config/routes.rb
Rails.application.routes.draw do
root 'billboards#index'

  resources :artists do
    resources :songs
  end

  resources :billboards do
    resources :songs
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
end

app/models/billboard.rb
class Billboard < ApplicationRecord
end

app/models/song.rb
class Song < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def new
    @artist = Artist.new
  end

  def edit
    artist = Artist.find(params[:id])
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save?
      redirect_to artists_path
    else
      render :new
    end
  end

  def update
    @artist = Artist.find(params[:id])
    if @artist.save?
      redirect_to artists_path
    else
      render :new
    end
  end


def artist_params
  params.require(:artist).permit(:name, :artist)
end

end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  def index
    @billboards = Billboard.all
  end

  def show
    @billboards = Billboard.find(params[:id])
  end

  def new
    @billboard = Billboard.new
  end

  def edit
  end

  def create
    @billboards = Billboard.new(billboard_params)

    if @billboards.save
      redirect_to billboards_path
    else
      render :new
    end
  end


def billboard_params
  params.require(:billboard).permit(:name, :artist)
end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def show
    @song = Song.find(params[:id])
  end

  def new
    @song = Song.new
  end

  def edit
  end

  def create
    @song = Song.new(billboard_params)

    if song.save?
      redirect_to songs_path
    else
      render :new
    end
  end


def song_params
  params.require(:song).permit(:name, :artist)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<h1>Artists#index</h1>
<p>Find me in app/views/artists/index.html.erb</p>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<h1>Artists#show</h1>
<p>Find me in app/views/artists/show.html.erb</p>

app/views/billboards/edit.html.erb
<h1>Billboards#edit</h1>
<p>Find me in app/views/billboards/edit.html.erb</p>

app/views/billboards/index.html.erb
<h1> Billboards </h1>
<p><%= link_to 'New Billboard', new_billboard_path %></p>
<% @billboards.each do |billboard| %>
  <h2><%= billboard.name %></h2>
  <%= link_to 'Show Billboard', billboards_path(billboard) %>
<% end %>

app/views/billboards/new.html.erb
<h1>Billboards#new</h1>
<h1> New Billboard </h1>
<%= form_for @billboard do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :artist %>
  <%= f.text_field :artist %>

  <%= f.submit %>
<% end %>

app/views/billboards/show.html.erb
<h1>Billboards#show</h1>
<p>Find me in app/views/billboards/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BillboardApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<h1>Songs#index</h1>
<p>Find me in app/views/songs/index.html.erb</p>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<p>Find me in app/views/songs/show.html.erb</p>